################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

[en.params]
# copyright
copyright = "Copyright by your company"

# <a target="_blank" rel="noopener noreferrer" href="">

################################### French language #####################################
[fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2

[fr.params]
# copyright
home = "Accueil"
copyright = "Copyright by your company"