############# English navigation ##############


[[main]]
weight = 3
name = "Company"
hasChildren = true

[[main]]
weight = 1
parent = "Company"
name = "About Us"
url = "about/"

[[main]]
weight = 1
parent = "Company"
name = "How it Works"
url = "how-it-works/"

[[main]]
weight = 2
parent = "Company"
name = "FAQ"
url = "faqs/"

[[main]]
weight = 3
parent = "Company"
name = "Terms & Conditions"
url = "tnc/"

[[main]]
weight = 4
parent = "Company"
name = "Money Back"
url = "money-back/"

[[main]]
weight = 5
parent = "Company"
name = "Revision Policy"
url = "revision-policy/"

[[main]]
weight = 6
parent = "Company"
name = "Privacy Policy"
url = "privacy-policy/"



[[main]]
name = "Pricing"
url = "pricing/"
weight = 6


  
[[main]]
name = "Contact Us"
url = "contact/"
weight = 8

[[main]]
name = "Blog"
url = "blog/"
weight = 9



### footer menus
# footer_menu_1
[[footer_menu_1]]
name = "Our Story"
url = "about/"
weight = 1

[[footer_menu_1]]
name = "FAQs"
url = "faqs/"
weight = 2

[[footer_menu_1]]
name = "How It Works"
url = "how-it-works/"
weight = 3




# footer_menu_2
[[footer_menu_2]]
name = "Academic Writing Help"
url = "academic-writing-help/"
weight = 1

[[footer_menu_2]]
name = "Visa Applications Help"
url = "visa-applications-help/"
weight = 2

[[footer_menu_2]]
name = "GPA Calculation Help"
url = "gpa-calculation-help/"
weight = 3



# footer_menu_3
[[footer_menu_3]]
name = "Pricing"
url = "pricing/"
weight = 1

[[footer_menu_3]]
name = "Blog"
url = "blog/"
weight = 2

[[footer_menu_3]]
name = "Contact"
url = "contact/"
weight = 3


# footer_menu_4
[[footer_menu_4]]
name = "Terms"
url = "tnc/"
weight = 1


[[footer_menu_4]]
name = "Money Back"
url = "money-back/"
weight = 3

[[footer_menu_4]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 4

[[footer_menu_4]]
name = "Revision Policy"
url = "revision-policy/"
weight = 4


# footer_menu_5
[[footer_menu_5]]
name = "Author"
url = "author/awab-husameldin/"
weight = 1

[[footer_menu_5]]
name = "Blog"
url = "blog/"
weight = 2

[[footer_menu_5]]
name = "Blog Details"
url = "blog/post-1/"
weight = 3

[[footer_menu_5]]
name = "Career"
url = "career/"
weight = 4

[[footer_menu_5]]
name = "Career Single"
url = "career/digital-marketing-paid-media-manager/"
weight = 5